/* http://yensdesign.com/tutorials/forumsdatabase/schemaFull.jpg */

DROP TABLE IF EXISTS forumPollsOptions;
DROP TABLE IF EXISTS forumPost;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS forumSubcategory;
DROP TABLE IF EXISTS forumCategory;

CREATE TABLE forumCategory (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(64) NOT NULL UNIQUE,
	description TEXT,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE forumSubcategory (
	id INT PRIMARY KEY AUTO_INCREMENT,
	idCategory INT NOT NULL,
	title VARCHAR(45) NOT NULL UNIQUE,
	description TEXT,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY(idCategory) REFERENCES forumCategory(id)	 
);

CREATE TABLE user (
	id INT PRIMARY KEY AUTO_INCREMENT,
	pseudo VARCHAR(16) NOT NULL UNIQUE,
	password VARCHAR(256) NOT NULL,
	email VARCHAR(128) NOT NULL UNIQUE,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	karma FLOAT(2,1),
	ip VARCHAR(20) NOT NULL
);

CREATE TABLE forumPost (
	id INT PRIMARY KEY AUTO_INCREMENT,
	idSubcategory INT NOT NULL,
	idUser INT NOT NULL,
	idParentPost INT NOT NULL,
	title VARCHAR(90) NOT NULL UNIQUE,
	content TEXT NOT NULL,
	isPoll BOOLEAN NOT NULL DEFAULT 0,
	isEdited BOOLEAN NOT NULL DEFAULT 0,
	createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	ip VARCHAR(20) NOT NULL,
	CONSTRAINT FOREIGN KEY(idSubcategory) REFERENCES forumSubcategory(id),
	CONSTRAINT FOREIGN KEY(idUser) REFERENCES user(id),
	CONSTRAINT FOREIGN KEY(idParentPost) REFERENCES forumPost(id)
);

CREATE TABLE forumPollsOptions (
	id INT PRIMARY KEY AUTO_INCREMENT,
	idPost INT NOT NULL,
	title VARCHAR(64) NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY(idPost) REFERENCES forumPost(id)
);